const SECTIONS={"REVISIÓN EXTERNA Y CARROCERÍA":["Óxidos visibles","Vidrios, parabrisas, espejos","Estado y desgaste de neumáticos","Grabado de Patentes","Llantas / Ruedas","Molduras y plásticos"],"LUCES":["Luz interior","Posición delantera","Luces Bajas","Luces Altas","Intermitentes delanteros","Neblineros delanteros","Luces laterales delanteras","Posición Traseras","Luces de Freno","Luz de Patente","Neblineros traseros","Laterales Traseras"],"NEUMÁTICOS":["Delantero Derecho","Delantero Izquierdo","Trasero Derecho","Trasero Izquierdo","Repuesto","Todos iguales?","Pernos llantas"],"MOTOR Y COMPONENTES":["Aceite de Motor","Refrigerante","Líquido de freno","Líquido de embrague","Líquido de dirección","Batería","Sistema de Carga (alternador)","Vapores sistema de combustión","Hermeticidad de escape","Sonido de motor","Filtro de Aire","Fugas visibles","Correas de accesorios / Mangueras"],"FRENOS":["Discos y Pastillas delanteras","Discos y Pastillas traseras","Cañerías, Calipers, Flexibles","Freno de Mano"],"SUSPENSIÓN Y DIRECCIÓN":["Amortiguadores Delanteros","Cazoletas Delanteras","Bieletas Delanteras","Amortiguadores Traseros","Cazoletas Traseras","Juego rodamientos de rueda","Juego en terminales de dirección"],"REVISIÓN INTERIOR Y EQUIPAMIENTO":["Asistencia reversa (sensores / cámara)","Limpia Parabrisas Plumillas / Lavaparabrisas","Reseteo de Aceite / Mantención / IOLM","Extintor","Cierre Centralizado","Inspección de tablero (luces de alertas)","Bocina","Alzavidrios Eléctricos","Espejos Eléctricos","Comandos al volante","Telecomando y Señalizadores","Aire Acondicionado","Calefacción","Estado de Tapicería","Radio o Multimedia","Cinturones de seguridad"],"DIAGNÓSTICO SCANNER":["Scanner (DTCs) de módulos","Verificación de VIN","Verificación de kilometraje","Verificación de Compresión (si está disponible)"],"PRUEBA DE RUTA":["Se realiza?","Estabilidad RPM en Ralenti","Balanceo","Alineación (cargas evidentes)","Eficiencia, equilibrio y ruidos de frenado","Estado transmisión automática","Funcionamiento Embrague (mecánico)","Temperatura Motor","Sonidos de suspensión","Funcionamiento 4x4","Sistema escape, humos, estanqueidad"]};
const DB='CF_MANT_V5',ACTIVE='CF_MANT_ACTIVE_V5';let current=null,timer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').toLowerCase();
function records(){try{const x=JSON.parse(localStorage.getItem(DB)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function writeRecords(a){localStorage.setItem(DB,JSON.stringify(a))}
function newRecord(){return{id:'CF-'+Date.now(),created:new Date().toISOString(),updated:new Date().toISOString(),meta:{fecha:new Date().toISOString().slice(0,10)},items:{},conclusion:''}}
function extra(sec,item){if(sec==='NEUMÁTICOS'&&/Derecho|Izquierdo|Repuesto/.test(item))return['Medida neumático','Profundidad dibujo (mm)'];if(item==='Batería')return['Voltaje','CCA / estado'];if(item==='Líquido de freno')return['% humedad / medición'];if(/Discos y Pastillas/.test(item))return['Espesor / desgaste','Detalle por eje'];return[]}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showHome(){saveNow(true);$('#formView').classList.add('hidden');$('#homeView').classList.remove('hidden');$('#bottomBar').classList.add('hidden');renderHistory();scrollTo(0,0)}
function showForm(){$('#homeView').classList.add('hidden');$('#formView').classList.remove('hidden');$('#bottomBar').classList.remove('hidden');fillMeta();renderChecklist();scrollTo(0,0)}
function create(){current=newRecord();saveNow(true);showForm()}
function fillMeta(){$$('[data-meta]').forEach(i=>i.value=current?.meta?.[i.dataset.meta]||'');$('#conclusion').value=current?.conclusion||''}
function renderChecklist(){const host=$('#checklist');host.innerHTML='';Object.entries(SECTIONS).forEach(([sec,items])=>{const box=document.createElement('section');box.className='section';box.innerHTML='<h2>'+sec+'</h2>';items.forEach(item=>{const key=slug(sec+'_'+item),d=current.items[key]||{photos:[],extras:{}};const el=document.createElement('div');el.className='item';el.dataset.key=key;el.innerHTML=`<div class="item-title">${esc(item)}</div><div class="status"><button data-v="ok">✓ OK</button><button data-v="warn">! Atención</button><button data-v="bad">✕ Intervención</button><button data-v="na">N/A</button></div><input class="obs" placeholder="Observación" value="${esc(d.obs)}"><div class="extras">${extra(sec,item).map(x=>`<label>${esc(x)}<input data-extra="${esc(x)}" value="${esc((d.extras||{})[x])}"></label>`).join('')}</div><div class="photo"><b>Fotos</b><div class="photo-actions"><label class="photo-btn">📷 Tomar foto<input class="photo-input camera" type="file" accept="image/*" capture="environment"></label><label class="photo-btn gallery">▣ Galería<input class="photo-input gallery-in" type="file" accept="image/*" multiple></label></div><div class="thumbs"></div></div>`;if(d.status)el.querySelector(`[data-v="${d.status}"]`)?.classList.add('active');box.appendChild(el);bindItem(el,key)});host.appendChild(box)});counts()}
function bindItem(el,key){el.querySelectorAll('.status button').forEach(b=>b.onclick=()=>{el.querySelectorAll('.status button').forEach(x=>x.classList.remove('active'));b.classList.add('active');schedule();counts()});el.querySelector('.obs').oninput=schedule;el.querySelectorAll('[data-extra]').forEach(i=>i.oninput=schedule);el.querySelectorAll('.photo-input').forEach(inp=>inp.onchange=async e=>{for(const f of [...e.target.files]){const pic=await compress(f);current.items[key]=current.items[key]||{extras:{},photos:[]};current.items[key].photos=current.items[key].photos||[];current.items[key].photos.push(pic)}e.target.value='';renderPhotos(el,key);saveNow(true)});renderPhotos(el,key)}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=850,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.55))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function renderPhotos(el,key){const box=el.querySelector('.thumbs'),pics=current.items[key]?.photos||[];box.innerHTML='';pics.forEach((src,i)=>{const w=document.createElement('div');w.className='thumb';w.innerHTML=`<img src="${src}" alt="Foto de revisión"><button type="button">×</button>`;w.querySelector('img').onclick=()=>{$('#fullPhoto').src=src;$('#photoModal').classList.remove('hidden')};w.querySelector('button').onclick=ev=>{ev.stopPropagation();pics.splice(i,1);renderPhotos(el,key);saveNow(true)};box.appendChild(w)})}
function collect(){if(!current)return;$$('[data-meta]').forEach(i=>current.meta[i.dataset.meta]=i.value);current.conclusion=$('#conclusion').value;$$('.item').forEach(el=>{const key=el.dataset.key,x=current.items[key]||{photos:[],extras:{}};x.photos=x.photos||[];x.status=el.querySelector('.status .active')?.dataset.v||'';x.obs=el.querySelector('.obs').value;x.extras={};el.querySelectorAll('[data-extra]').forEach(i=>x.extras[i.dataset.extra]=i.value);current.items[key]=x})}
function saveNow(silent=false){if(!current)return;collect();current.updated=new Date().toISOString();let a=records(),i=a.findIndex(x=>x.id===current.id);if(i<0)a.unshift(current);else a[i]=current;try{writeRecords(a);localStorage.setItem(ACTIVE,current.id);$('#saveState').textContent='Guardado ✓ '+new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});if(!silent)alert('Revisión guardada.')}catch(e){$('#saveState').textContent='Error al guardar';if(!silent)alert('No se pudo guardar. Puede haberse llenado el almacenamiento del navegador.')}}
function schedule(){clearTimeout(timer);$('#saveState').textContent='Guardando…';timer=setTimeout(()=>saveNow(true),300)}
function openRecord(id){const r=records().find(x=>x.id===id);if(!r)return alert('No se encontró la revisión.');current=JSON.parse(JSON.stringify(r));localStorage.setItem(ACTIVE,id);showForm()}
function deleteRecord(id){if(!confirm('¿Eliminar esta revisión?'))return;writeRecords(records().filter(x=>x.id!==id));if(localStorage.getItem(ACTIVE)===id)localStorage.removeItem(ACTIVE);renderHistory()}
function renderHistory(){const a=records(),h=$('#historyList');if(!a.length){h.innerHTML='<div class="empty">Aún no hay revisiones guardadas.</div>';return}h.innerHTML=a.map(x=>`<div class="history-card"><div class="title">${esc(x.meta?.patente||'Sin patente')} · ${esc(x.meta?.marca||'')} ${esc(x.meta?.modelo||'')}</div><small>${esc(x.meta?.cliente||'Sin cliente')} · ${x.updated?new Date(x.updated).toLocaleString('es-CL'):''}</small><div class="history-actions"><button onclick="openRecord('${x.id}')">Abrir / continuar</button><button class="danger" onclick="deleteRecord('${x.id}')">Eliminar</button></div></div>`).join('')}
function counts(){let c={ok:0,warn:0,bad:0,na:0};$$('.status .active').forEach(b=>c[b.dataset.v]++);$('#okCount').textContent=c.ok;$('#warnCount').textContent=c.warn;$('#badCount').textContent=c.bad;$('#naCount').textContent=c.na}
function prepareReport(){saveNow(true);$('#printFolio').textContent='Folio: '+current.id+' · Fecha informe: '+new Date().toLocaleDateString('es-CL');$$('.item').forEach(el=>{const d=current.items[el.dataset.key]||{};el.classList.toggle('print-hide',!(['ok','warn','bad'].includes(d.status)||((d.photos||[]).length>0)))});$$('.section').forEach(sec=>sec.classList.toggle('print-hide',![...sec.querySelectorAll('.item')].some(el=>!el.classList.contains('print-hide'))))}
function clearReportFilter(){$$('.item,.section').forEach(el=>el.classList.remove('print-hide'))}
$('#createBtn').onclick=create;$('#refreshBtn').onclick=renderHistory;$('#backBtn').onclick=showHome;$('#navHistory').onclick=showHome;$('#navSave').onclick=()=>saveNow(false);
$('#navPdf').onclick=()=>{prepareReport();window.print();setTimeout(clearReportFilter,500)};
$('#navTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});$$('[data-meta]').forEach(i=>i.oninput=schedule);$('#conclusion').oninput=schedule;
window.openRecord=openRecord;window.deleteRecord=deleteRecord;renderHistory();
const closePhotoModal=()=>{$('#photoModal').classList.add('hidden');$('#fullPhoto').src=''};$('#closePhoto').onclick=closePhotoModal;$('#photoModal').onclick=e=>{if(e.target.id==='photoModal')closePhotoModal()};

/* V10: Google Drive, permiso restringido drive.file */
const GOOGLE_CLIENT_ID='752698643419-le70dldkh83r5jtmu5gba94pp3u9e49n.apps.googleusercontent.com';
const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file';
const DRIVE_FOLDER_KEY='CF_DRIVE_FOLDER_V10';
let driveAccessToken='';
function safeFilePart(v){return String(v||'').trim().replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,'_').slice(0,60)||'Sin_dato'}
function driveFileName(){const m=current?.meta||{},date=m.fecha||new Date().toISOString().slice(0,10);return `${date}_${safeFilePart(m.patente)}_${safeFilePart(m.marca)}_${safeFilePart(m.modelo)}.pdf`}
async function ensureDriveToken(){if(driveAccessToken)return driveAccessToken;if(!window.google?.accounts?.oauth2)throw new Error('Google todavía está cargando. Intenta nuevamente en unos segundos.');return await new Promise((resolve,reject)=>{const tc=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:DRIVE_SCOPE,callback:r=>{if(r.error)return reject(new Error(r.error));driveAccessToken=r.access_token;resolve(driveAccessToken)}});tc.requestAccessToken({prompt:'consent'})})}
async function driveFetch(url,opt={}){const token=await ensureDriveToken();opt.headers={...(opt.headers||{}),Authorization:'Bearer '+token};let r=await fetch(url,opt);if(r.status===401){driveAccessToken='';opt.headers.Authorization='Bearer '+await ensureDriveToken();r=await fetch(url,opt)}if(!r.ok)throw new Error((await r.text())||('Google Drive respondió '+r.status));return r}
async function getOrCreateDriveFolder(){let id=localStorage.getItem(DRIVE_FOLDER_KEY);if(id){try{await driveFetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?fields=id,name,trashed');return id}catch(e){localStorage.removeItem(DRIVE_FOLDER_KEY)}}const r=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Cero Falla Revisiones',mimeType:'application/vnd.google-apps.folder'})});const d=await r.json();localStorage.setItem(DRIVE_FOLDER_KEY,d.id);return d.id}
async function makePdfBlob(){prepareReport();const form=$('#formView'),bar=$('#bottomBar'),top=$('.top-actions');bar.classList.add('hidden');top.classList.add('hidden');const old={bg:form.style.background,color:form.style.color,pad:form.style.padding};form.style.background='#fff';form.style.color='#111';form.style.padding='12px';try{const canvas=await html2canvas(form,{scale:1.35,useCORS:true,backgroundColor:'#fff',windowWidth:1000});const {jsPDF}=window.jspdf,pdf=new jsPDF('p','mm','a4'),pw=210,ph=297,margin=8,usable=pw-margin*2,img=canvas.toDataURL('image/jpeg',.86),imgH=canvas.height*usable/canvas.width;let left=imgH,y=margin;pdf.addImage(img,'JPEG',margin,y,usable,imgH);left-=ph-margin*2;while(left>0){pdf.addPage();y=margin-(imgH-left);pdf.addImage(img,'JPEG',margin,y,usable,imgH);left-=ph-margin*2}return pdf.output('blob')}finally{form.style.background=old.bg;form.style.color=old.color;form.style.padding=old.pad;top.classList.remove('hidden');bar.classList.remove('hidden');clearReportFilter()}}
async function uploadPdfToDrive(blob){const folderId=await getOrCreateDriveFolder(),boundary='cf_'+Date.now(),meta={name:driveFileName(),mimeType:'application/pdf',parents:[folderId]},head='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: application/pdf\r\n\r\n',tail='\r\n--'+boundary+'--',body=new Blob([head,blob,tail],{type:'multipart/related; boundary='+boundary});const r=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return await r.json()}
async function savePdfToDrive(){if(!current)return alert('Abre una revisión primero.');saveNow(true);const b=$('#navDrive'),old=b.innerHTML;b.disabled=true;b.innerHTML='⏳<span>Guardando</span>';try{await ensureDriveToken();const blob=await makePdfBlob(),f=await uploadPdfToDrive(blob);alert('PDF guardado en Google Drive ✓\n\n'+f.name)}catch(e){console.error(e);alert('No se pudo guardar en Drive.\n\n'+e.message)}finally{b.disabled=false;b.innerHTML=old}}
$('#navDrive').onclick=savePdfToDrive;
