const SECTIONS={"REVISIÓN EXTERNA Y CARROCERÍA": ["Óxidos visibles", "Vidrios, parabrisas, espejos", "Estado y desgaste de neumáticos", "Grabado de Patentes", "Llantas / Ruedas", "Molduras y plásticos"], "LUCES": ["Luz interior", "Posición delantera", "Luces Bajas", "Luces Altas", "Intermitentes delanteros", "Neblineros delanteros", "Luces laterales delanteras", "Posición Traseras", "Luces de Freno", "Luz de Patente", "Neblineros traseros", "Laterales Traseras"], "NEUMÁTICOS": ["Delantero Derecho", "Delantero Izquierdo", "Trasero Derecho", "Trasero Izquierdo", "Repuesto", "Todos iguales?", "Pernos llantas"], "MOTOR Y COMPONENTES": ["Aceite de Motor", "Refrigerante", "Líquido de freno", "Líquido de embrague", "Líquido de dirección", "Batería", "Sistema de Carga (alternador)", "Vapores sistema de combustión", "Hermeticidad de escape", "Sonido de motor", "Filtro de Aire", "Fugas visibles", "Correas de accesorios / Mangueras"], "FRENOS": ["Discos y Pastillas delanteras", "Discos y Pastillas traseras", "Cañerías, Calipers, Flexibles", "Freno de Mano"], "SUSPENSIÓN Y DIRECCIÓN": ["Amortiguadores Delanteros", "Cazoletas Delanteras", "Bieletas Delanteras", "Amortiguadores Traseros", "Cazoletas Traseras", "Juego rodamientos de rueda", "Juego en terminales de dirección"], "REVISIÓN INTERIOR Y EQUIPAMIENTO": ["Asistencia reversa (sensores / cámara)", "Limpia Parabrisas Plumillas / Lavaparabrisas", "Reseteo de Aceite / Mantención / IOLM", "Extintor", "Cierre Centralizado", "Inspección de tablero (luces de alertas)", "Bocina", "Alzavidrios Eléctricos", "Espejos Eléctricos", "Comandos al volante", "Telecomando y Señalizadores", "Aire Acondicionado", "Calefacción", "Estado de Tapicería", "Radio o Multimedia", "Cinturones de seguridad"], "DIAGNÓSTICO SCANNER": ["Scanner (DTCs) de módulos", "Verificación de VIN", "Verificación de kilometraje", "Verificación de Compresión (si está disponible)"], "PRUEBA DE RUTA": ["Se realiza?", "Estabilidad RPM en Ralenti", "Balanceo", "Alineación (cargas evidentes)", "Eficiencia, equilibrio y ruidos de frenado", "Estado transmisión automática", "Funcionamiento Embrague (mecánico)", "Temperatura Motor", "Sonidos de suspensión", "Funcionamiento 4x4", "Sistema escape, humos, estanqueidad"]};
const DB='CF_MANT_V5', ACTIVE='CF_MANT_ACTIVE_V5'; let current=null, timer=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').toLowerCase();
function records(){try{const x=JSON.parse(localStorage.getItem(DB)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function writeRecords(a){localStorage.setItem(DB,JSON.stringify(a))}
function newRecord(){return{id:'CF-'+Date.now(),created:new Date().toISOString(),updated:new Date().toISOString(),meta:{fecha:new Date().toISOString().slice(0,10)},items:{},conclusion:''}}
function extra(sec,item){if(sec==='NEUMÁTICOS'&&/Derecho|Izquierdo|Repuesto/.test(item))return['Medida neumático','Profundidad dibujo (mm)'];if(item==='Batería')return['Voltaje','CCA / estado'];if(item==='Líquido de freno')return['% humedad / medición'];if(/Discos y Pastillas/.test(item))return['Espesor / desgaste','Detalle por eje'];return[]}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showHome(){saveNow(true);$('#formView').classList.add('hidden');$('#homeView').classList.remove('hidden');$('#bottomBar').classList.add('hidden');renderHistory();scrollTo(0,0)}
function showForm(){$('#homeView').classList.add('hidden');$('#formView').classList.remove('hidden');$('#bottomBar').classList.remove('hidden');fillMeta();renderChecklist();scrollTo(0,0)}
function create(){current=newRecord();saveNow(true);showForm()}
function fillMeta(){$$('[data-meta]').forEach(i=>i.value=current?.meta?.[i.dataset.meta]||'');$('#conclusion').value=current?.conclusion||''}
function renderChecklist(){const host=$('#checklist');host.innerHTML='';Object.entries(SECTIONS).forEach(([sec,items])=>{const box=document.createElement('section');box.className='section';box.innerHTML='<h2>'+sec+'</h2>';items.forEach(item=>{const key=slug(sec+'_'+item),d=current.items[key]||{photos:[],extras:{}};const el=document.createElement('div');el.className='item';el.dataset.key=key;el.innerHTML=`<div class="item-title">${esc(item)}</div><div class="status"><button data-v="ok">✓ OK</button><button data-v="warn">! Atención</button><button data-v="bad">✕ Intervención</button><button data-v="na">N/A</button></div><input class="obs" placeholder="Observación" value="${esc(d.obs)}"><div class="extras">${extra(sec,item).map(x=>`<label>${esc(x)}<input data-extra="${esc(x)}" value="${esc((d.extras||{})[x])}"></label>`).join('')}</div><div class="photo"><b>Fotos</b><div class="photo-actions"><label class="photo-btn">📷 Tomar foto<input class="photo-input camera" type="file" accept="image/*" capture="environment"></label><label class="photo-btn gallery">▣ Galería<input class="photo-input gallery-in" type="file" accept="image/*" multiple></label></div><div class="thumbs"></div></div>`;if(d.status)el.querySelector(`[data-v="${d.status}"]`)?.classList.add('active');box.appendChild(el);bindItem(el,key)});host.appendChild(box)});counts()}
function bindItem(el,key){el.querySelectorAll('.status button').forEach(b=>b.onclick=()=>{el.querySelectorAll('.status button').forEach(x=>x.classList.remove('active'));b.classList.add('active');schedule();counts()});el.querySelector('.obs').oninput=schedule;el.querySelectorAll('[data-extra]').forEach(i=>i.oninput=schedule);el.querySelectorAll('.photo-input').forEach(inp=>inp.onchange=async e=>{for(const f of [...e.target.files]){const pic=await compress(f);current.items[key]=current.items[key]||{extras:{},photos:[]};current.items[key].photos=current.items[key].photos||[];current.items[key].photos.push(pic)}e.target.value='';renderPhotos(el,key);saveNow(true)});renderPhotos(el,key)}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=850,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.55))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function renderPhotos(el,key){const box=el.querySelector('.thumbs'),pics=current.items[key]?.photos||[];box.innerHTML='';pics.forEach((src,i)=>{const w=document.createElement('div');w.className='thumb';w.innerHTML=`<img src="${src}"><button type="button">×</button>`;w.querySelector('button').onclick=()=>{pics.splice(i,1);renderPhotos(el,key);saveNow(true)};box.appendChild(w)})}
function collect(){if(!current)return;$$('[data-meta]').forEach(i=>current.meta[i.dataset.meta]=i.value);current.conclusion=$('#conclusion').value;$$('.item').forEach(el=>{const key=el.dataset.key,x=current.items[key]||{photos:[],extras:{}};x.photos=x.photos||[];x.status=el.querySelector('.status .active')?.dataset.v||'';x.obs=el.querySelector('.obs').value;x.extras={};el.querySelectorAll('[data-extra]').forEach(i=>x.extras[i.dataset.extra]=i.value);current.items[key]=x})}
function saveNow(silent=false){if(!current)return;collect();current.updated=new Date().toISOString();let a=records(),i=a.findIndex(x=>x.id===current.id);if(i<0)a.unshift(current);else a[i]=current;try{writeRecords(a);localStorage.setItem(ACTIVE,current.id);$('#saveState').textContent='Guardado ✓ '+new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});if(!silent)alert('Revisión guardada.')}catch(e){$('#saveState').textContent='Error al guardar';if(!silent)alert('No se pudo guardar. Puede haberse llenado el almacenamiento del navegador.');}}
function schedule(){clearTimeout(timer);$('#saveState').textContent='Guardando…';timer=setTimeout(()=>saveNow(true),300)}
function openRecord(id){const r=records().find(x=>x.id===id);if(!r)return alert('No se encontró la revisión.');current=JSON.parse(JSON.stringify(r));localStorage.setItem(ACTIVE,id);showForm()}
function deleteRecord(id){if(!confirm('¿Eliminar esta revisión?'))return;writeRecords(records().filter(x=>x.id!==id));if(localStorage.getItem(ACTIVE)===id)localStorage.removeItem(ACTIVE);renderHistory()}
function renderHistory(){const a=records(),h=$('#historyList');if(!a.length){h.innerHTML='<div class="empty">Aún no hay revisiones guardadas.</div>';return}h.innerHTML=a.map(x=>`<div class="history-card"><div class="title">${esc(x.meta?.patente||'Sin patente')} · ${esc(x.meta?.marca||'')} ${esc(x.meta?.modelo||'')}</div><small>${esc(x.meta?.cliente||'Sin cliente')} · ${x.updated?new Date(x.updated).toLocaleString('es-CL'):''}</small><div class="history-actions"><button onclick="openRecord('${x.id}')">Abrir / continuar</button><button class="danger" onclick="deleteRecord('${x.id}')">Eliminar</button></div></div>`).join('')}
function counts(){let c={ok:0,warn:0,bad:0,na:0};$$('.status .active').forEach(b=>c[b.dataset.v]++);$('#okCount').textContent=c.ok;$('#warnCount').textContent=c.warn;$('#badCount').textContent=c.bad;$('#naCount').textContent=c.na}
$('#createBtn').onclick=create;$('#refreshBtn').onclick=renderHistory;$('#backBtn').onclick=showHome;$('#navHistory').onclick=showHome;$('#navSave').onclick=()=>saveNow(false);$('#navPdf').onclick=()=>{
 saveNow(true);
 $('#printFolio').textContent='Folio: '+current.id+' · Fecha informe: '+new Date().toLocaleDateString('es-CL');
 $$('.item').forEach(el=>{
   const key=el.dataset.key, d=current.items[key]||{};
   const included=['ok','warn','bad'].includes(d.status) || ((d.photos||[]).length>0);
   el.classList.toggle('print-hide',!included);
 });
 $$('.section').forEach(sec=>{
   const visible=[...sec.querySelectorAll('.item')].some(el=>!el.classList.contains('print-hide'));
   sec.classList.toggle('print-hide',!visible);
 });
 window.print();
 setTimeout(()=>{$$('.item,.section').forEach(el=>el.classList.remove('print-hide'))},500);
};$('#navTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});$$('[data-meta]').forEach(i=>i.oninput=schedule);$('#conclusion').oninput=schedule;
window.openRecord=openRecord;window.deleteRecord=deleteRecord;renderHistory();
